### ISSUE TITLE
Add option to only display warning

### ISSUE THREAD

**Issue by dsnoeck** [christiangalsterer/bitbucket-prsquash-plugin#2]
This plugin is interesting but too restrictive.
In our case, just a warning "_Several un-squashed commits_" before merging would be enough. Because it might happen that we want to keep several commit in the history.
Similar to #1, but in more general approach.

**Comment by christiangalsterer** [comment]
@dsnoeck: Thanks for your request. Unfortunately the Bitbucket plugin system doesn't have support to only display a warning message for a merge check.

**Comment by dsnoeck** [comment]
@christiangalsterer, thanks for the reply. We will then split in several PR if necessary.
